### PR TITLE
Create R CMD check GitHub Action

### PR DESCRIPTION
**Pull request by mhpob**
Adds the R CMD check GitHub action via [`usethis::use_github_action('check-standard')`](https://usethis.r-lib.org/reference/use_github_action.html). Should be triggered by pushes or PRs to main or dev.

Figure this may be easier than linking to the R-universe build checks?

Can help ID things like those outlined in #185, #186, and #190. Maybe even lead to polishing off #106!

### CODE REVIEW

**Review by jdpye — APPROVED** [review]
I'd be eager to try this out, would like a little more build-automation in our GitHub incarnation here.

**Comment by mhpob** [comment]
If there's discomfort with this, the exact same (or nearly the exact same) actions are safely operational in other packages from friends of OTN:

https://github.com/hugomflavio/actel/tree/master/.github/workflows
https://github.com/SimonDedman/gbm.auto/tree/master/.github/workflows
https://github.com/benjaminhlina/soapcheckr/tree/main/.github/workflows
https://github.com/mhpob/matos/tree/master/.github/workflows
https://github.com/mhpob/otndo/tree/main/.github/workflows

**Comment by mhpob** [comment]
@jdpye I added style and documentation actions as well, so asking for a re-review.

Style action result example: https://github.com/mhpob/matos/commit/bf04a0fc46dda3a03d16bc803bc70c8b6b6b8330
Document action runs roxygenize upon edits to anything in R/

**Review by jdpye — APPROVED** [review]
Going to have to doublecheck the secrets on this repo, but this all looks fine.

**Pull request merged**
