### PR TITLE
Pass R CMD check with no errors

### PR DESCRIPTION
**Pull request by mhpob**
R CMD check should complete without errors (only warnings!) after review/acceptance of  this.

List of changes:
- R CMD check GitHub Action only fails if ERRORs are found. Should later be changed to WARNINGs as those are addressed (can't have ERRORs or WARNINGs to be on CRAN)
- Fixes the "There are ::: calls to the package's namespace in its code. A package almost never needs to use ::: for its own objects" warning in R CMD check.
- Since the internal namespace references are removed, a developer should "load all" to have access to internal functions (`devtools::load_all`)
- Add `util-intern_pkg_man.R` to Rbuildignore to remove dependency on `usethis`
- Add undeclared dependency on `units`
- Moved `knitr`, `rmarkdown`, and `methods` to Suggests to reduce direct dependencies
- `fasttime` dependency has been removed. Documentation still needs to be updated
- Uses `\dontrun` to skip examples that won't work until fix for #202 
- Uses `\dontrun` to skip examples needing vdat.exe
- Fixes broken examples in `make_transition3` and `kml_to_csv`
- Uses `try` to catch and print the example error in examples for `glatos_detections`, `glatos_receivers`, and `glatos_animals`
- Changes and `T` or `F` in the examples to `TRUE` or `FALSE` since R CMD check is apparently extremely opinionated

### CODE REVIEW

**Comment by mhpob** [comment]
@jdpye could I ask you (or anyone else) to run `devtools::document` or `roxygen2::roxygenize` on this PR and commit? I have a weird system specific thing preventing me from doing so.

It should fix the last R CMD check error... Or let it progress down the line to the next error it hasn't gotten to yet.

**Comment by jdpye** [comment]
I'll give it a shot today, yep!

**Comment by jdpye** [comment]
Mike, I think you won out!

**Comment by mhpob** [comment]
I hope you weren't getting hammered with all of those notices, but if you were...

GLATOS NOW PASSES R CMD CHECK!


(ish. Warnings still need to be addressed, but now if we don't get the pretty green check marks after a commit you know that something is probably not good.)

**Review by jdpye — APPROVED** [review]

**Comment by chrisholbrook** [comment]
> GLATOS NOW PASSES R CMD CHECK!

@mhpob Wow! Can't thank you enough for incredible mop up effort here! also @jdpye for keeping momentum.

Confirming as of now (https://github.com/ocean-tracking-network/glatos/commit/f016ab1538634e6368da7b80411046d2251ef253) passes `devtools::check()` for me locally:

image

**Pull request merged**
