### PR TITLE
vrl2csv bug fix for paths that contain spaces.

### LINKED ISSUE #137: vrl2csv fails to produce csv (without error) when paths contain spaces
In GitLab by @chrisholbrook on Jun 5, 2021, 16:59

Quote path to vrl source files and csv output. Also, check that output files exist and error or warn if not.

### PR DESCRIPTION
**Pull request by mhpob**
Should close #137.

### CODE REVIEW

**Comment by mhpob** [comment]
Closing this to branch off dev

**Comment by mhpob** [comment]
To test:

```
# Access internal VLR
myVRL <- system.file("extdata", "VR2W_109924_20110718_1.vrl",
                     package="glatos")

# Create tempdir with spaces in the file path
temp_dir <- tempdir()
test_dir <- file.path(temp_dir, 'test dir')
dir.create(test_dir)

# Copy internal VLR to tempir
file.copy(myVRL, test_dir)

# Check files
list.files(test_dir, full.names = T, pattern = '*.vrl')

# Run vrl2csv
glatos::vrl2csv(list.files(test_dir, full.names = T, pattern = '*.vrl'),
        outDir = test_dir,
        vueExePath = 'C:/Program Files (x86)/VEMCO/VUE')

# Check that CSV was created
list.files(test_dir)
readLines(list.files(test_dir, full.names = T, pattern = '*.csv'), 10)

# Delete tempdir
unlink(temp_dir, recursive = T)
```

**Review by chrisholbrook — COMMENTED** [review]
@mhpob What was the reason for this? This is a breaking change because it previously returned the file paths, which were used elsewhere, so it needs to be reverted, at least for now.

**Comment by mhpob** [comment]
@chrisholbrook that was an error on my part. Changing that back to `return` and moving to after the warning will have it behave normally.

**Pull request merged**
