### PR TITLE
Update tests to testthat 3e

### LINKED ISSUE #196: testthat with windows executables and externally referenced files are not working
we're experiencing some errors with the merge checking GHA, when it's running the tests in `testthat`. the ones built to work with VUE.exe and some of the .RDA files that are in the package need to be either excluded or have their references fixed up.

### LINKED ISSUE #201: Remove functions deprecated in testthat edition 3
After upgrading to testthat edition 3, some tests are throwing warnings about deprecated functions. All calls to deprecated functions should be removed, perhaps following this guidance: https://www.tidyverse.org/blog/2022/02/upkeep-testthat-3/

E.g., 

> Warning (test-read_glatos_receivers.r:1:1): (code run outside of `test_that()`)
> `context()` was deprecated in the 3rd edition.
> Backtrace:
>     ▆
>  1. └─testthat::context("Check read_glatos_receivers") at test-read_glatos_receivers.r:1:1
>  2.   └─testthat:::edition_deprecate(3, "context()")

### LINKED ISSUE #209: Ubuntu and MacOS create files of different sizes in `make_frames` test
Following a R CMD check on GitHub Actions, the test frame for make_frames is [189413 bytes on Ubuntu](https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677120018#step:6:2672) and [226246 bytes on MacOS](https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677119585#step:6:2668). It is the expected ~30k bytes on Windows and the [developer's local Linux](https://github.com/ocean-tracking-network/glatos/pull/204#issuecomment-1904517945) so doesn't fail the test.

### PR DESCRIPTION
**Pull request by mhpob**
- Closes #196.
- Closes #201.
- Closes #209.
- Mostly addresses #205.
   - [`convert_glatos_to_att`](https://github.com/ocean-tracking-network/glatos/blob/dev/R/util-convert_glatos_to_att.r#L44) and the [`walleye_att` data](https://github.com/ocean-tracking-network/glatos/blob/dev/data-raw/intdata-walleye_att.r#L19) still need to be fixed to close that issue, but it doesn't error any tests so I didn't touch it in this PR.
- `inst/testdata` can be removed as necessary testing data is in `data` or `tests/testthat/testdata`.
   - Did not do this as I didn't want to introduce something that could be a breaking change without explicit permission.

Two tests are currently skipped due to #202. Addressing the root cause involves changing the data (which may be a breaking change) and so is beyond the scope of this PR.

Tests are overly-repetitive in order to keep the smallest scope possible, as outlined in https://r-pkgs.org/testing-basics.html

### CODE REVIEW

**Comment by mhpob** [comment]
Most warnings now related to:

- #198
  - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2430
- many-to-many matches warning from `dplyr`
  - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2387
  - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2451
  - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2483
  - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2527
  - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2566
  - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2608
- Deprecation of external vector use in `dplyr`
   - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2641
   - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2663
   - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2685
   - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2707
- Missing dependency on the zip package
 - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2747
- #202
 - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:8519
 - https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:8529
   
Errors that don't arise on my machine, but do on GH Actions:
- [This, where I literally can't see a difference...](https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2737)
- [A make frames error that needs to be sussed out](https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2740)
- [times all shift ahead an hour on CI -- possibly due to local time conversion on the runner?](https://github.com/ocean-tracking-network/glatos/actions/runs/7535529485/job/20511643541?pr=204#step:6:2777)

**Comment by jdpye** [comment]
I think this is the solve for all the make_frames errors: https://github.com/STAT545-UBC/Discussion/issues/451#issuecomment-385731301

adding .data$varname instead of hanging the var_name all by itself everywhere should crush those.
The time shift one should be sortable. we should explicitly name a time zone in the tests.

**Comment by jdpye** [comment]
The read-workbook check passes on my local against the plain dev branch. so we may have some CI-related discrepancies there to work out.

**Comment by jdpye** [comment]
> The read-workbook check passes on my local against the plain dev branch. so we may have some CI-related discrepancies there to work out.

sorry, this is interesting to the problem only because I'm in Europe right now. The timezone is weird here. Should have triggered something if not including the timezone was the issue

**Comment by jdpye** [comment]
While there's not a difference between the blue shark data frames that I can find yet, I suspect that both of their CRSes are incorrectly set. It ought to be EPSG:4326, not 3426. The error persists across both the example and the instanced data so it's a problem but not part of the test failure.

**Comment by mhpob** [comment]
@jdpye c71b570 looks to be addressing an R CMD check error, rather than an error from testing. See discussion in #190: Could be addressed with adding .data$column_name (rather than .$column_name) or creating the column names with no binding as NULL objects at the top of the function (i.e., giving them a dummy binding).

**Comment by jdpye** [comment]
true, that's the error I'm trying to squish there. I tried it with .data$var_names and it gave me a new version of the same error, saying that .data is undefined. I assume it didn't take the rlang import correctly, but the .$ appears to squash the bug and i am all about bringing down the number of extra lines these test runs print.

**Comment by mhpob** [comment]
Pulled in changes from #206 and #207. Failing tests are still those outlined above. Note that these are a subset of the tests failing in `main`/`dev` (i.e., some of the adjustments in the PR solve test warnings and failures).

This PR's testing suite:
[ FAIL 14 | WARN 7 | SKIP 9 | PASS 193 ]

Current `dev` testing suite:
[ FAIL 16 | WARN 35 | SKIP 0 | PASS 26 ]

**Comment by mhpob** [comment]
> The read-workbook check passes on my local against the plain dev branch. so we may have some CI-related discrepancies there to work out.

@jdpye it looks like there are differences between Windows, MacOS, and Ubuntu that have caused this and some other tests to fail.

[MacOS](https://github.com/ocean-tracking-network/glatos/actions/runs/7614871740/job/20738138394#step:6:2283) and [Windows](https://github.com/ocean-tracking-network/glatos/actions/runs/7614871740/job/20738138733#step:6:2286) do not shift time, but [Ubuntu](https://github.com/ocean-tracking-network/glatos/actions/runs/7614871740/job/20738139386#step:6:2285) does.

[MacOS](https://github.com/ocean-tracking-network/glatos/actions/runs/7614871740/job/20738138394#step:6:2681) and [Ubuntu](https://github.com/ocean-tracking-network/glatos/actions/runs/7614871740/job/20738139386#step:6:2681) also create files 6x the size of Windows when running `make_frames` (these checks do not fail on Windows).

**Comment by haydento** [comment]
I used linux to develop and test make_frames.  What do you mean Ubuntu shifts time and creates files 6x the size of windows?


Todd
________________________________
From: mhpob ***@***.***>
Sent: Monday, January 22, 2024 12:44
To: ocean-tracking-network/glatos ***@***.***>
Cc: Hayden, Todd A ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ocean-tracking-network/glatos] Update tests to testthat 3e (PR #204)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



The read-workbook check passes on my local against the plain dev branch. so we may have some CI-related discrepancies there to work out.

@jdpye<https://github.com/jdpye> it looks like there are differences between Windows, MacOS, and Ubuntu that have caused this and some other tests to fail.

MacOS<https://github.com/ocean-tracking-network/glatos/actions/runs/7614871740/job/20738138394#step:6:2283> and Windows<https://github.com/ocean-tracking-network/glatos/actions/runs/7614871740/job/20738138733#step:6:2286> do not shift time, but Ubuntu<https://github.com/ocean-tracking-network/glatos/actions/runs/7614871740/job/20738139386#step:6:2285> does.

MacOS<https://github.com/ocean-tracking-network/glatos/actions/runs/7614871740/job/20738138394#step:6:2681> and Ubuntu<https://github.com/ocean-tracking-network/glatos/actions/runs/7614871740/job/20738139386#step:6:2681> also create files 6x the size of Windows when running make_frames (these checks do not fail on Windows). @haydento<https://github.com/haydento> were you using Windows when writing make_frames?

**Comment by mhpob** [comment]
@haydento two different issues on different functions.

Shifting time:
[`read_glatos_workbook` test failing on Ubuntu](https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677120018#step:6:2710) by shifting the time one hour ahead. The release, current, and old versions of Ubuntu error in the same manner. No similar error for [Windows](https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677119776#step:6:2649) or [MacOS](https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677119585#step:6:2642)

Large files:
The test frame for `make_frames` is [189413 bytes on Ubuntu](https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677120018#step:6:2672) and [226246 bytes on MacOS](https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677119585#step:6:2668). It is the expected ~30k bytes on Windows and so doesn't fail the test.

**Comment by haydento** [comment]
Can you provide me with the script that is causing the issues on Ubuntu?  I would like to test it on my machine.

Todd
________________________________
From: mhpob ***@***.***>
Sent: Monday, January 22, 2024 13:03
To: ocean-tracking-network/glatos ***@***.***>
Cc: Hayden, Todd A ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ocean-tracking-network/glatos] Update tests to testthat 3e (PR #204)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@haydento<https://github.com/haydento> two different issues on different functions.

Shifting time:
read_glatos_workbook test failing on Ubuntu<https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677120018#step:6:2710> by shifting the time one hour ahead. The release, current, and old versions of Ubuntu error in the same manner. No similar error for Windows<https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677119776#step:6:2649> or MacOS<https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677119585#step:6:2642>

Large files:
The test frame for make_frames is 189413 bytes on Ubuntu<https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677120018#step:6:2672> and 226246 bytes on MacOS<https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677119585#step:6:2668>. It is the expected ~30k bytes on Windows and so doesn't fail the test.

**Comment by jdpye** [comment]
i think there are different DPI defaults across the OSes that might account for this difference. We could try and find the specific arguments to pass through to make things the same, but even then we're not likely to get the same image size down to the byte just from the different algorithms that may underlie the libraries we're using in the different OSes.

**Comment by mhpob** [comment]
@haydento it's running your tests for `read_glatos_workbook` and `make_frames`.

https://github.com/ocean-tracking-network/glatos/blob/dev/tests/testthat/test-read_glatos_workbook.r
https://github.com/ocean-tracking-network/glatos/blob/dev/tests/testthat/test-make_frames.r

**Comment by mhpob** [comment]
All tests pass, pending a fix for #202!

- updated blue_shark_att and blue_shark_erddap_att as they were based on faulty CRS specification (#205). May be a breaking change so willing to roll that back!
- set a lower-limit test for make_frames as discussed in #209 
- #202 still causes two tests to fail

**Comment by jdpye** [comment]
I think we can put this in dev, the last tests that we're dodging now are waiting on data source changes/updates, so we don't have to stand on this while those things are sorted. #202

**Review by jdpye — APPROVED** [review]
big sweeping fix-ups, but i like the re-org and the goal of getting ready for testthat3e will be very beneficial to us. carve-outs for the lingering problems that are documented in other tickets can be removed as we repair those issues.

**Pull request merged**
